baseURL = 'https://javchudutch.com/'

title = 'Ja Vchu Dutch - Learn Dutch together'
theme = 'ananke'
defaultContentLanguage = 'uk'
enableRobotsTXT = true

[frontmatter]
lastmod = ['lastmod', ':fileModTime', ':default']
date = [':filename', ':default']

[pagination]
pagerSize = 100

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[languages]

[languages.uk]
disabled = false
languageCode = 'uk'
languageDirection = ''
languageName = 'Українська'
weight = 0
title = 'Ja Vchu Dutch - вчимо нідерландську мову разом'
[languages.uk.menus]
[[languages.uk.menus.main]]
name = 'Публікації'
pageRef = '/posts'
weight = 1
[[languages.uk.menus.main]]
name = 'Ресурси'
pageRef = '/resources'
weight = 2
[[languages.uk.menus.main]]
name = 'Про мене'
pageRef = '/about'
weight = 3
[[languages.uk.menus.main]]
name = 'Контакт'
pageRef = '/contact'
weight = 4
[languages.uk.params]
[languages.uk.params.consent]
[[languages.uk.params.consent.items]]
title = 'Google Anaytics'
description = 'Ми використовуємо Google Analytics для збору анонімних даних про відвідувачів нашого сайту.'
is_functional = false
script_file = 'ga.js'

[languages.nl]
disabled = false
languageCode = 'nl'
languageDirection = ''
languageName = 'Nederlands'
weight = 1
title = 'Ja Vchu Dutch - Leren Nederlands samen'
[languages.nl.menus]
[[languages.nl.menus.main]]
name = 'Publicaties'
pageRef = '/posts'
weight = 1
[[languages.nl.menus.main]]
name = 'Bronnen'
pageRef = '/resources'
weight = 2
[[languages.nl.menus.main]]
name = 'Over mij'
pageRef = '/about'
weight = 3
[[languages.nl.menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 4
[[languages.nl.params.consent.items]]
title = 'Google Anaytics'
description = 'We gebruiken Google Analytics om anonieme gegevens over bezoekers van onze site te verzamelen.'
is_functional = false
script_file = 'ga.js'

[params]
site_logo = "images/logo.jpg"
favicon = "img/favicon/favicon.ico"
author = "Ja Vchu Dutch"
mainSections = ["posts"]
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[params.ananke.social.instagram]
username = 'javchudutch'
[params.ananke.social.facebook]
username = 'javchudutch'
[params.ananke.social.email]
username = 'info@javchudutch.com'
[params.ananke.social.buymeacoffee]
username = 'javchudutch'

[[params.ananke.social.networks]]
slug = "email"
label = "Email"
icon = "envelope"     # font awesome free icon name
profile = "mailto:%s"
link = "mailto:"
[params.ananke.social.networks.particles]
body = "permalink"
subject = "title"

[[params.ananke.social.networks]]
slug = "facebook"
label = "Facebook"
color = "#3b5998"
profile = "https://www.facebook.com/%s"
icon = "facebook"                               # font awesome brand icon name
link = "https://facebook.com/sharer/sharer.php"
[params.ananke.social.networks.particles]
u = "permalink"

[[params.ananke.social.networks]]
slug = "instagram"
label = "Instagram"
color = "#e1306c"
profile = "https://www.instagram.com/%s/"
icon = "instagram"                        # font awesome brand icon name

[[params.ananke.social.networks]]
slug = "buymeacoffee"
label = "Buy me a coffee"
color = "#f5d607"
profile = "https://buymeacoffee.com/%s"
icon = "buymeacoffee"                   # font awesome brand icon name
share = false

[params.ananke.social.follow]
new_window_icon = false
networks = ["facebook", "instagram", "email", "buymeacoffee"]

[params.ananke.social.share]
icons = true
sharetext = true
networks = ["facebook", "instagram", "email", "buymeacoffee"]

[[params.consent.items]]
title = 'Google Anaytics'
description = 'We use Google Analytics to collect anonymous data about visitors to our site.'
is_functional = false
script_file = 'ga.js'
